### ISSUE TITLE
MassProspecting SDK

### ISSUE THREAD

**Issue by leandrosardi** [MassProspecting/docs#127]
This is related with #64 that requried a the `basic.rb` process.
This is related with #111.

This requirement is important to outsource the development of new profie-integrations

## Abstract

**Definitions:** Server-Side and Client-Side

- The server-side processes are those processes with direct connection to the database.

- The server-side processes are those processes that operate the database trough the MassProspecting's REST-API.

There are 5 processes that run at the server side:

- ingest.rb and import.rb
- plan.rb
- rule.rb
- timeline.rb

There are 2 processes that run at the clients side:

- basic.rb
- profile.rb

There is an hibrid process `launch` who runs at the server-side (have direct access to the database) but starts/stops the client-side processes.

- lauch.rb

**Definitions:** Skeleton-Classes and Stub-Classes

- The skeleton-classes are Ruby ORM classes that inherit from `Sequel::Model`. Skeleton-classes run at the server side.

- The stub-classes are the equivalent of the skeleton-classes at the client-side. The base-line stub-classes replicates the facade of the skeleton-classes, and call them through the REST-API to perform the operations.

(diagram)

**Definitions:** Stub-Classes Lines

There are 3 types of stub-classes:

- base line: The base-line stub-classes replicates the facade of the skeleton-classes, and call them through the REST-API to perform the operations.

- first line: The first-line stub-classes inherit from the base_line and they implement the [driver design pattern](https://docs.specflow.org/projects/specflow/en/latest/Guides/DriverPattern.html)

(diagram example of profile first-line drivers)

- end-user lines: The end-user stub-classes ingerit from the first-line, and they are drivers too. They open-source and the community can develop and share their own drivers too.

(classes inheritance chart)

## Design

**Design Part 1:**

- Create a new repository called `massprospecting/mass-client`.

- Create a new repository called `massprospecting/sdk`.

**Design Part 2:**

- The `mass-client` includes all the base-line and first-line stub-classes.

- The `sdk` includes all the end-user-lines stub-classes.

**Design Part 3:**

- The `mass-client` includes the source code of 2 client-side processes (profile, basic)

- The `mass.client` library has a command to launch the client-side processes from terminal (launch, profile, basic).

**Design Part 4:**

- The `launch` process will connect the client-nodes via SSH to perform the starting/stopping of client-side processes.

- The `sdk` library requires installation of proper environment.

- The `sdk` references to the [leandrosardi/environment](https://github.com/leandrosardi/environment) repository where you can find `sh` script to run in fresh installations of Ubuntu 20.04.

- The `sdk` references to the [leandrosardi/environment](https://github.com/leandrosardi/environment) repository where you can find a dockerfile too.

**Design Part 5:**

- The SDK will have a examples requiring to the `mass-client`, and also the requiring all the end-user stub-classes in the same repository

- The end-user uses `mass-client` to operate his MassProspecting account throug the REST-API

- The end-user uses `sdk` to run processes locally, with integrations provided by them or others.

- If the end-user develops his own integrations, he must provide a registration hash-descritor too.

- If the sdk will proivides a script to run registration of all required end-user-line classes

**Design Part 6:** Collaboration

- End-users can form the `mass-sdk` and create a pull-request to get their integrations shared with the community.

- Pull requests are approved and merged by @leandrosardi

- When an end-user creates a pull-requests, his inegrations must be placed at `/lib/<name of user>-<id of user>`

- New merged integrations are upserted automatically to the main **account node** and each **sub account node** by a process called `publisher.rb`.

## Requirement Server-Side

- launcher runs 1 `basic.rb` process for each account in the node where those accounts are hosted.

## Requirement Client-Side

- add support for the `ignore-hostname` parameter to both the `basic` and `profile` processes.

- `launch.rb` must include the api key when launch a process (`launch.rb` used to run the `profile.rb` processes with no passing an API key, because it was not designed for a multi-user platform)

## Requirement at Both Sides

- Track SDK version used.

**Comment by leandrosardi** [comment]
Same problem when I call a function and pass the logger as a parameter:

```ruby
require_relative '../lib/simple_cloud_logging'

BlackStack::Logger.set(
    nesting_assertion: true,
)

# create a logger
l = BlackStack::LocalLogger.new("assertion.log")

def check_number(number, logger: nill)
    l = logger || Blackstack::DummyLogger.new(nil)

    l.logs "Checking... "
    if number == 3
        l.yes 
    else
        l.no 
    end
end

begin
    l.blank_line
    l.logs "Looking for number 3... "

    numbers = [0, 1, 2, 3, 4, 5]

    numbers.each do |i|
        l.logs "#{i}... " 

        check_number(i, logger: l)
        i += 1

        l.done
    end

    l.done
rescue => e
    l.error(e)
end
```

```
=> ["/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_instance.rb:290:in `eval'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_instance.rb:290:in `evaluate_ruby'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_instance.rb:659:in `handle_line'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_instance.rb:261:in `block (2 levels) in eval'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_instance.rb:260:in `catch'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_instance.rb:260:in `block in eval'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_instance.rb:259:in `catch'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_instance.rb:259:in `eval'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/repl.rb:77:in `block in repl'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/repl.rb:67:in `loop'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/repl.rb:67:in `repl'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/repl.rb:38:in `block in start'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/input_lock.rb:61:in `__with_ownership'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/input_lock.rb:78:in `with_ownership'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/repl.rb:38:in `start'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/repl.rb:15:in `start'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/pry_class.rb:194:in `start'",
 "/home/leandro/.rvm/gems/ruby-3.1.2/gems/pry-0.14.2/lib/pry/core_extensions.rb:45:in `pry'",
 "/home/leandro/code/simple_cloud_logging/lib/baselogger.rb:147:in `logs'",
 "/home/leandro/code/simple_cloud_logging/lib/locallogger.rb:46:in `logs'",
 "assertion6.rb:13:in `check_number'",
 "assertion6.rb:30:in `block in <main>'",
 "assertion6.rb:27:in `each'",
 "assertion6.rb:27:in `<main>'"]
```

**Comment by leandrosardi** [comment]
## Tasks

- develop process `launch.rb` 
- develop add parameter `ignore_hostname`
