### ISSUE TITLE
glitch: running 2 enrichments on the same company

### ISSUE THREAD

**Issue by leandrosardi** [MassProspecting/docs#187]
- earch enrichment performed is updating the status of the both enrichments

- Re-upload lead picture:

```
2024-08-08 16:00:38: Set profile state :enrichment... Error: Error calling update endpoint: The picture_url_dropbox 'https://dl.dropboxusercontent.com/scl/fi/0y25nxelcz9yp76ei5ukt/98afc6f4-faff-4e23-b1ca-30ec384c50d0.fdf4ec57-7ecb-409d-87c0-b6a0f2366add.png?rlkey=0luu7toduxqw3nhciquvp6od2&dl=0' for Profile is not reachable.
/home/blackstack/code/mass.slave/lib/skeletons.rb:108:in `base_update'
/home/blackstack/code/mass.slave/extensions/mass.commons/models/skeleton/profile.rb:403:in `update'
/home/blackstack/code/mass.slave/views/api1.0/update.erb:15:in `__tilt_7881160'
/usr/local/rvm/gems/ruby-3.1.2/gems/tilt-2.4.0/lib/tilt/template.rb:207:in `bind_call'
/usr/local/rvm/gems/ruby-3.1.2/gems/tilt-2.4.0/lib/tilt/template.rb:207:in `evaluate'
/usr/local/rvm/gems/ruby-3.1.2/gems/tilt-2.4.0/lib/tilt/template.rb:102:in `render'
/usr/local/rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/base.rb:863:in `render'
/usr/local/rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/base.rb:711:in `erb'
/home/blackstack/code/mass.slave/app.rb:652:in `block in <main>'
/usr/local/rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/base.rb:1697:in `call'
/usr/local/rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/base.rb:1697:in `block in compile!'
/usr/local/rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/base.rb:1030:in `block (3 levels) in route!'
/usr/local/rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/base.rb:1049:in `route_eval'
/usr/local/rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/base.rb:1030:in `block (2 levels) in route!'
/usr/local/rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/base.rb:1078:in `block in process_route'
/usr/local/rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/base.rb:1076:in `catch'
/usr/local/rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/base.rb:1076:in `process_route'
/usr/local/rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/base.rb:1028:in `block in route!'
/usr/local/rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/base.rb:1025:in `each'
/usr/local/rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/base.rb:1025:in `route!'
/usr/local/rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/base.rb:1147:in `block in dispatch!'
/usr/local/rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/base.rb:1119:in `block in invoke'
/usr/local/rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/base.rb:1119:in `catch'
/usr/local/rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/base.rb:1119:in `invoke'
/usr/local/rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/base.rb:1142:in `dispatch!'
/usr/local/rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/base.rb:956:in `block in call!'
/usr/local/rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/base.rb:1119:in `block in invoke'
/usr/local/rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/base.rb:1119:in `catch'
/usr/local/rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/base.rb:1119:in `invoke'
/usr/local/rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/base.rb:956:in `call!'
/usr/local/rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/base.rb:945:in `call'
/usr/local/rvm/gems/ruby-3.1.2/gems/rack-contrib-2.3.0/lib/rack/contrib/try_static.rb:35:in `call'
/usr/local/rvm/gems/ruby-3.1.2/gems/rack-contrib-2.3.0/lib/rack/contrib/try_static.rb:35:in `call'
/usr/local/rvm/gems/ruby-3.1.2/gems/rack-contrib-2.3.0/lib/rack/contrib/try_static.rb:35:in `call'
/usr/local/rvm/gems/ruby-3.1.2/gems/rack-contrib-2.3.0/lib/rack/contrib/try_static.rb:35:in `call'
/usr/local/rvm/gems/ruby-3.1.2/gems/rack-contrib-2.3.0/lib/rack/contrib/try_static.rb:35:in `call'
/usr/local/rvm/gems/ruby-3.1.2/gems/rack-2.2.9/lib/rack/session/abstract/id.rb:266:in `context'
/usr/local/rvm/gems/ruby-3.1.2/gems/rack-2.2.9/lib/rack/session/abstract/id.rb:260:in `call'
/usr/local/rvm/gems/ruby-3.1.2/gems/rack-2.2.9/lib/rack/logger.rb:17:in `call'
/usr/local/rvm/gems/ruby-3.1.2/gems/rack-2.2.9/lib/rack/common_logger.rb:38:in `call'
/usr/local/rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/base.rb:255:in `call'
/usr/local/rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/base.rb:248:in `call'
/usr/local/rvm/gems/ruby-3.1.2/gems/rack-2.2.9/lib/rack/head.rb:12:in `call'
/usr/local/rvm/gems/ruby-3.1.2/gems/rack-2.2.9/lib/rack/method_override.rb:24:in `call'
/usr/local/rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/show_exceptions.rb:22:in `call'
/usr/local/rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/base.rb:218:in `call'
/usr/local/rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/base.rb:2004:in `call'
/usr/local/rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/base.rb:1564:in `block in call'
/usr/local/rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/base.rb:1780:in `synchronize'
/usr/local/rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/base.rb:1564:in `call'
/usr/local/rvm/gems/ruby-3.1.2/gems/puma-5.6.8/lib/puma/configuration.rb:252:in `call'
/usr/local/rvm/gems/ruby-3.1.2/gems/puma-5.6.8/lib/puma/request.rb:77:in `block in handle_request'
/usr/local/rvm/gems/ruby-3.1.2/gems/puma-5.6.8/lib/puma/thread_pool.rb:340:in `with_force_shutdown'
/usr/local/rvm/gems/ruby-3.1.2/gems/puma-5.6.8/lib/puma/request.rb:76:in `handle_request'
/usr/local/rvm/gems/ruby-3.1.2/gems/puma-5.6.8/lib/puma/server.rb:443:in `process_client'
/usr/local/rvm/gems/ruby-3.1.2/gems/puma-5.6.8/lib/puma/thread_pool.rb:147:in `block in spawn_thread'
/usr/local/rvm/gems/ruby-3.1.2/gems/blackstack-core-1.2.26/lib/functions.rb:196:in `update'
/usr/local/rvm/gems/ruby-3.1.2/gems/blackstack-core-1.2.26/lib/functions.rb:217:in `update'
/home/blackstack/code/mass-sdk/p/profile.rb:736:in `<main>'
```

**Comment by leandrosardi** [comment]
This issue couldn't be replicated.
