### ISSUE TITLE
glitch: scraping LPF

### ISSUE THREAD

**Issue by leandrosardi** [MassProspecting/docs#253]
## CLI

```
ruby profile.rb api_key=474cfd74-8c81-43b0-89de-657badf55229 id=c4d9f77d-34d7-45d4-8876-bae867751ea0 ignore-hostname=yes force-profile-run=yes headless=no run-once=yes inboxcheck=no connectioncheck=no scraping=yes id_job=eed8f99f-aa00-450b-96e2-0d82ecde6b3e enrichment=no outreach=no 
```

## Error

```
The file 6dafa47b-7a8c-480a-a2f9-f1676fd09cc9.png was not downloaded.
/usr/local/rvm/gems/ruby-3.1.2/gems/mass-client-1.0.11/lib/first-line/profile_rpa.rb:230:in `download_image_0'
/usr/local/rvm/gems/ruby-3.1.2/gems/mass-client-1.0.11/lib/first-line/profile_rpa.rb:248:in `download_image'
/home/blackstack/code/mass-sdk/lib/source_types/LinkedIn_PublicFeed.rb:189:in `block in do'
/home/blackstack/code/mass-sdk/lib/source_types/LinkedIn_PublicFeed.rb:165:in `each'
/home/blackstack/code/mass-sdk/lib/source_types/LinkedIn_PublicFeed.rb:165:in `do'
/home/blackstack/code/mass-sdk/p/profile.rb:666:in `block in 
'
/home/blackstack/code/mass-sdk/p/profile.rb:658:in `each'
/home/blackstack/code/mass-sdk/p/profile.rb:658:in `
'
```

**Comment by leandrosardi** [comment]
## GPT Prompt

```
I open a browser from Ruby using selenium/webdriver.

Then I call the driver.exectue_script execute this javascript function:

ruby
            js0 = "
                async function downloadImage(imageSrc, filename) {
                    const image = await fetch(imageSrc)
                    const imageBlog = await image.blob()
                    const imageURL = URL.createObjectURL(imageBlog)
                  
                    const link = document.createElement('a')
                    link.href = imageURL
                    link.download = filename
                    document.body.appendChild(link)
                    link.click()
                    document.body.removeChild(link)
                }
                downloadImage('#{url}', '#{filename}')
            "
#binding.pry
            driver.execute_script(js0)
```

## GPT Answer

The Ruby code you provided is designed to download an image using JavaScript through Selenium WebDriver. However, there are a few things to check to ensure it works as intended:

1. Asynchronous Execution: Since the JavaScript function is async, it may not complete before Selenium moves on to the next command. To handle this, you can wrap the function call inside a Promise and return the result to Selenium.

2. JavaScript Execution Context: Ensure that the JavaScript execution context is appropriate. If the page context changes (e.g., new tabs, iframes), this could interfere with the script.

Here's an adjusted version of your Ruby code:

```ruby
js0 = "
    function downloadImage(imageSrc, filename) {
        return new Promise(async (resolve, reject) => {
            try {
                const image = await fetch(imageSrc);
                const imageBlob = await image.blob();
                const imageURL = URL.createObjectURL(imageBlob);

                const link = document.createElement('a');
                link.href = imageURL;
                link.download = filename;
                document.body.appendChild(link);
                link.click();
                document.body.removeChild(link);

                resolve('Download initiated');
            } catch (error) {
                reject(error);
            }
        });
    }
    return downloadImage('#{url}', '#{filename}');
"

# Execute the script and wait for the promise to resolve
result = driver.execute_script(js0)
puts result # This should print "Download initiated" if successful
```

## Key Points:

- Promise Handling: By returning a Promise in the JavaScript code, Selenium will wait for the asynchronous operation to complete.

- Error Handling: The code includes basic error handling, which can be useful for debugging if something goes wrong.

- Result Checking: The result variable will hold the string "Download initiated" if the download process started successfully.

## Troubleshooting Tips:

- Ensure Correct URL and Filename: Double-check that the url and filename variables in Ruby are correctly set.

- Cross-Origin Issues: If you're downloading from a different domain, ensure that CORS policies don't block the request.

- Browser Settings: Depending on your browser settings, automatic downloads might be blocked. Ensure that the browser is configured to allow downloads via JavaScript.

This code should work correctly in most scenarios. If you encounter specific issues, please provide details so I can assist further.

**Comment by leandrosardi** [comment]
This is happening again.

**Comment by leandrosardi** [comment]
Still happening.
