### ISSUE TITLE
glitch: Apollo RPA is crashing browser.

### ISSUE THREAD

**Issue by leandrosardi** [MassProspecting/docs#262]
A scraping job failes with the error message shown below:

```
unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: chrome=116.0.5845.97)
#0 0x55fc286dee23 
#1 0x55fc284075f6 
#2 0x55fc283ee567 
#3 0x55fc283ed28a 
#4 0x55fc283ed84f 
#5 0x55fc283fdb47 
#6 0x55fc283feca2 
#7 0x55fc2841180f 
#8 0x55fc2841610b 
#9 0x55fc283edef1 
#10 0x55fc28411449 
#11 0x55fc2847f27e 
#12 0x55fc28466de3 
#13 0x55fc2843aa7b 
#14 0x55fc2843b81e 
#15 0x55fc286a0638 
#16 0x55fc286a4507 
#17 0x55fc286aec4c 
#18 0x55fc286a5136 
#19 0x55fc286739cf 
#20 0x55fc286c8b98 
#21 0x55fc286c8d68 
#22 0x55fc286d7cb3 
#23 0x7f1bd105b609 start_thread
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/response.rb:55:in `assert_ok'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/http/common.rb:83:in `new'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/http/common.rb:83:in `create_response'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/http/default.rb:104:in `request'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/bridge.rb:620:in `execute'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/bridge.rb:555:in `find_elements_by'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/common/search_context.rb:78:in `find_elements'
/home/blackstack/code1/sdk/lib/profile_rpa/apollo_rpa.rb:15:in `block in wait_results'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/common/wait.rb:56:in `until'
/home/blackstack/code1/sdk/lib/profile_rpa/apollo_rpa.rb:13:in `wait_results'
/home/blackstack/code1/sdk/lib/source_types/Apollo_PeopleSearch.rb:83:in `do'
/home/blackstack/code1/sdk/p/profile.rb:666:in `block in 
'
/home/blackstack/code1/sdk/p/profile.rb:658:in `each'
/home/blackstack/code1/sdk/p/profile.rb:658:in `
'
```

And all further jobs will faile with this other message shown below:

```
invalid session id
#0 0x564f4a260e23 
#1 0x564f49f895f6 
#2 0x564f49fbbf26 
#3 0x564f49fe8f16 
#4 0x564f49fe50ad 
#5 0x564f49fe4815 
#6 0x564f49f56853 
#7 0x564f4a222638 
#8 0x564f4a226507 
#9 0x564f4a230c4c 
#10 0x564f4a227136 
#11 0x564f4a1f59cf 
#12 0x564f49f54d78 
#13 0x7f0c29ff1083 __libc_start_main
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/response.rb:55:in `assert_ok'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/http/common.rb:83:in `new'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/http/common.rb:83:in `create_response'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/http/default.rb:104:in `request'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/bridge.rb:620:in `execute'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/bridge.rb:94:in `get'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/common/navigation.rb:32:in `to'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/common/driver.rb:135:in `get'
/home/blackstack/code1/sdk/lib/source_types/Apollo_PeopleSearch.rb:79:in `do'
/home/blackstack/code1/sdk/p/profile.rb:722:in `block in 
'
/home/blackstack/code1/sdk/p/profile.rb:714:in `each'
/home/blackstack/code1/sdk/p/profile.rb:714:in `
'
```

**Comment by leandrosardi** [comment]
Fixed after I did an upgrade of `w0201` from `VPS-1` to `VPS-3`.
