### ISSUE TITLE
glitch: `apollo.03` stopped working after I ran many seaches together, one after another.

### ISSUE THREAD

**Issue by leandrosardi** [MassProspecting/docs#264]
I think I abossed Apollo and now it is not showing up emails.

![Image](https://github.com/user-attachments/assets/4c5e5099-54cf-4df7-8acf-c52088e2255d)

```
ruby profile.rb api_key=f4261a96-aa1e-45fd-9658-5dd31cf654a1 api_url=https://s02.massprospecting.com:443 id=e0d74977-6296-4ac9-acdb-c01e20be18c5 ignore-hostname=yes force-profile-run=yes headless=no run-once=yes inboxcheck=no connectioncheck=no scraping=yes id_job=d1060fd8-5d23-47a9-8e23-982dfc6d544e enrichment=no outreach=no 
```

```
/home/leandro/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/net/protocol.rb:47:in `wait_readable'
/home/leandro/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/net/protocol.rb:47:in `ssl_socket_connect'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/net-http-0.2.2/lib/net/http.rb:1088:in `connect'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/net-http-0.2.2/lib/net/http.rb:995:in `do_start'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/net-http-0.2.2/lib/net/http.rb:984:in `start'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/faraday-net_http-2.1.0/lib/faraday/adapter/net_http.rb:145:in `request_via_request_method'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/faraday-net_http-2.1.0/lib/faraday/adapter/net_http.rb:130:in `request_with_wrapped_block'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/faraday-net_http-2.1.0/lib/faraday/adapter/net_http.rb:121:in `perform_request'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/faraday-net_http-2.1.0/lib/faraday/adapter/net_http.rb:66:in `block in call'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/faraday-2.3.0/lib/faraday/adapter.rb:45:in `connection'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/faraday-net_http-2.1.0/lib/faraday/adapter/net_http.rb:65:in `call'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/faraday-2.3.0/lib/faraday/request/url_encoded.rb:25:in `call'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/faraday-2.3.0/lib/faraday/rack_builder.rb:153:in `build_response'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/faraday-2.3.0/lib/faraday/connection.rb:445:in `run_request'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/faraday-2.3.0/lib/faraday/connection.rb:281:in `post'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/blackstack-core-1.2.28/lib/functions.rb:918:in `call_post'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/blackstack-core-1.2.28/lib/functions.rb:69:in `post'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/blackstack-core-1.2.28/lib/functions.rb:243:in `upsert'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/blackstack-core-1.2.28/lib/functions.rb:254:in `upsert'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/mass-client-1.0.17/lib/base-line/job.rb:39:in `block in upsert'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/mass-client-1.0.17/lib/base-line/job.rb:36:in `each'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/mass-client-1.0.17/lib/base-line/job.rb:36:in `upsert'
profile.rb:731:in `block in 
'
profile.rb:727:in `each'
profile.rb:727:in `
'```

**Comment by leandrosardi** [comment]
![Image](https://github.com/user-attachments/assets/fc15da5f-c2b8-4c7e-96d0-0ead4015d499)

**Comment by leandrosardi** [comment]
It resolved itself after 24 hours.

It seems there was a shadow banning.
