### ISSUE TITLE
glitch session deleted because of page crash

### ISSUE THREAD

**Issue by leandrosardi** [MassProspecting/docs#281]
## CLI

```
ruby profile.rb api_key=5a047930-f8d9-4485-9fce-82307fc1285c api_url=https://s02.massprospecting.com:443 id=bd2224c2-a8d3-4049-8b20-abf9d9b8e4c4 ignore-hostname=yes force-profile-run=yes headless=no run-once=yes inboxcheck=no connectioncheck=yes id_connectioncheck=923bfc59-58b0-4f11-ae27-604693d85b4b scraping=no enrichment=no outreach=no 
```

## Error

```
unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=116.0.5845.97)
#0 0x55f7c11e0e23 
#1 0x55f7c0f095f6 
#2 0x55f7c0ef1e4f 
#3 0x55f7c0ef172d 
#4 0x55f7c0ef065c 
#5 0x55f7c0ef05ce 
#6 0x55f7c0eef28a 
#7 0x55f7c0eef84f 
#8 0x55f7c0effb47 
#9 0x55f7c0f00ca2 
#10 0x55f7c0f1380f 
#11 0x55f7c0f1810b 
#12 0x55f7c0eefef1 
#13 0x55f7c0f13449 
#14 0x55f7c0f81563 
#15 0x55f7c0f68de3 
#16 0x55f7c0f3ca7b 
#17 0x55f7c0f3d81e 
#18 0x55f7c11a2638 
#19 0x55f7c11a6507 
#20 0x55f7c11b0c4c 
#21 0x55f7c11a7136 
#22 0x55f7c11759cf 
#23 0x55f7c11cab98 
#24 0x55f7c11cad68 
#25 0x55f7c11d9cb3 
#26 0x7f574d98e609 start_thread
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/response.rb:55:in `assert_ok'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/http/common.rb:83:in `new'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/http/common.rb:83:in `create_response'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/http/default.rb:104:in `request'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/bridge.rb:620:in `execute'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/bridge.rb:94:in `get'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/common/navigation.rb:32:in `to'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/common/driver.rb:135:in `get'
/home/blackstack/code1/sdk/lib/profile_rpa/linkedin.rb:259:in `connectioncheck'
/home/blackstack/code1/sdk/p/profile.rb:623:in `block in 
'
/home/blackstack/code1/sdk/p/profile.rb:616:in `each'
/home/blackstack/code1/sdk/p/profile.rb:616:in `
'
```

## Screenshot

![image](https://github.com/user-attachments/assets/072f33f8-bf15-4932-9863-e994e2610e7f)

**Comment by leandrosardi** [comment]
```
unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: headless chrome=116.0.5845.97)
#0 0x55bb69abfe23 
#1 0x55bb697e85f6 
#2 0x55bb697d0e4f 
#3 0x55bb697d072d 
#4 0x55bb697cf65c 
#5 0x55bb697cf5ce 
#6 0x55bb697ce28a 
#7 0x55bb697ce84f 
#8 0x55bb697deb47 
#9 0x55bb697dfca2 
#10 0x55bb697f280f 
#11 0x55bb697f710b 
#12 0x55bb697ceef1 
#13 0x55bb697f2449 
#14 0x55bb6986027e 
#15 0x55bb69847de3 
#16 0x55bb6981ba7b 
#17 0x55bb6981c81e 
#18 0x55bb69a81638 
#19 0x55bb69a85507 
#20 0x55bb69a8fc4c 
#21 0x55bb69a86136 
#22 0x55bb69a549cf 
#23 0x55bb69aa9b98 
#24 0x55bb69aa9d68 
#25 0x55bb69ab8cb3 
#26 0x7f200b9b9609 start_thread
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/response.rb:55:in `assert_ok'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/http/common.rb:83:in `new'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/http/common.rb:83:in `create_response'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/http/default.rb:104:in `request'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/bridge.rb:620:in `execute'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/bridge.rb:555:in `find_elements_by'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/common/search_context.rb:78:in `find_elements'
/home/blackstack/code1/sdk/lib/profile_rpa/linkedin.rb:269:in `connectioncheck'
/home/blackstack/code1/sdk/p/profile.rb:625:in `block in 
'
/home/blackstack/code1/sdk/p/profile.rb:618:in `each'
/home/blackstack/code1/sdk/p/profile.rb:618:in `
'
```

**Comment by leandrosardi** [comment]
I have a Ruby script using Selenium/Webdriver.
Such a Ruby script is running on Ubuntu 20.04 server (with no UI)

The script started filing again and again with the following error: 

"session deleted because of page crash 
from unknown error: cannot determine loading status
from tab crashed"

The exception were well handled, with retry managing and browser restarting.

But the only way the error stopped to happen was restarting the server.

How to prevent this to happen again?
