### ISSUE TITLE
glitch: on sending messages in Edward Ukaonu account.

### ISSUE THREAD

**Issue by leandrosardi** [MassProspecting/docs#286]
**LinkedIn Direct Messages** pushed from the Unibox are being processed as **LinkedIn Connection Requests**.

**Error Description:**

```
Lead is already a 1st connection.
/home/blackstack/code1/sdk/lib/outreach_types/LinkedIn_ConnectionRequest.rb:95:in `do'
/home/blackstack/code1/sdk/p/profile.rb:1100:in `block in 
'
/home/blackstack/code1/sdk/p/profile.rb:1016:in `each'
/home/blackstack/code1/sdk/p/profile.rb:1016:in `
'
```

![Image](https://github.com/user-attachments/assets/316bfced-1495-482f-a921-9d87b58f5eb2)

**Comment by leandrosardi** [comment]
## Migrations

```sql
alter table outreach_type add column if not exists id_outreach_type_for_further_outreaches uuid null references outreach_type(id);
```

**Comment by leandrosardi** [comment]
## Tasks

- Adapt access point `ajax/unibox/push.json`.
- Adapt methods of `OutreachType`: `parse` and `to_h`.
- Adapt initialization script.
- Run initialization script on master and sub-accounts.
