### ISSUE TITLE
glitch: error when starting an RPA profile / glitch after stopping a profile

### ISSUE THREAD

**Issue by leandrosardi** [MassProspecting/docs#287]
The solution to this issue #279 #281.

**Error:**

```
2024-10-01 09:23:27: Starting browser... Error: no such window: target window already closed
from unknown error: web view not found
  (Session info: headless chrome=116.0.5845.97)
#0 0x55e455338e23 <unknown>
#1 0x55e4550617a7 <unknown>
#2 0x55e455039691 <unknown>
#3 0x55e4550c5e0f <unknown>
#4 0x55e4550d8eb6 <unknown>
#5 0x55e4550c0de3 <unknown>
#6 0x55e455094a7b <unknown>
#7 0x55e45509581e <unknown>
#8 0x55e4552fa638 <unknown>
#9 0x55e4552fe507 <unknown>
#10 0x55e455308c4c <unknown>
#11 0x55e4552ff136 <unknown>
#12 0x55e4552cd9cf <unknown>
#13 0x55e455322b98 <unknown>
#14 0x55e455322d68 <unknown>
#15 0x55e455331cb3 <unknown>
#16 0x7f9c869aa609 start_thread
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/response.rb:55:in `assert_ok'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/http/common.rb:83:in `new'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/http/common.rb:83:in `create_response'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/http/default.rb:104:in `request'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/bridge.rb:620:in `execute'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/bridge.rb:258:in `set_window_rect'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/bridge.rb:216:in `resize_window'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/common/window.rb:119:in `resize_to'
/usr/local/rvm/gems/ruby-3.1.2/gems/mass-client-1.0.19/lib/first-line/profile_rpa.rb:350:in `driver'
/home/blackstack/code1/sdk/p/profile.rb:417:in `<main>'
2024-10-01 09:23:31: Stopping browser (2)... done
2024-10-01 09:23:31: Releasing resources... done
2024-10-01 09:23:31: Ending loop... done
2024-10-01 09:23:31: Calculating loop duration... done (3.706000046)
2024-10-01 09:23:31: Finished Loop!
```

**Comment by leandrosardi** [comment]
Another error I found:

```
Error: {"code"=>-1, "msg"=>"[kndknqg] is being used by [adspower@massprospecting.com] and is not allowed to open"}
/usr/local/rvm/gems/ruby-3.1.2/gems/adspower-client-1.0.14/lib/adspower-client.rb:133:in `block in start'
/usr/local/rvm/gems/ruby-3.1.2/gems/adspower-client-1.0.14/lib/adspower-client.rb:42:in `with_lock'
/usr/local/rvm/gems/ruby-3.1.2/gems/adspower-client-1.0.14/lib/adspower-client.rb:128:in `start'
/usr/local/rvm/gems/ruby-3.1.2/gems/adspower-client-1.0.14/lib/adspower-client.rb:196:in `driver2'
/usr/local/rvm/gems/ruby-3.1.2/gems/mass-client-1.0.28/lib/first-line/profile_rpa.rb:268:in `driver'
/usr/local/rvm/gems/ruby-3.1.2/gems/mass-client-1.0.28/lib/base-line/request.rb:22:in `start_browser'
/usr/local/rvm/gems/ruby-3.1.2/gems/mass-client-1.0.28/lib/base-line/request.rb:9:in `perform'
/home/blackstack/code1/sdk/p/profile.rb:353:in `block in <main>'
/home/blackstack/code1/sdk/p/profile.rb:350:in `each'
/home/blackstack/code1/sdk/p/profile.rb:350:in `<main>'
```

**Comment by leandrosardi** [comment]
The errors get fixed when I restart worker nodes:

```
ruby stop.rb --node=w01? --root && \
ruby start.rb --node=w01? --root
```
