### ISSUE TITLE
glitch on `launch2.rb`

### ISSUE THREAD

**Issue by leandrosardi** [MassProspecting/docs#290]
```
2024-10-01 10:36:12: Sleeping for 9.413211876 seconds... done
2024-10-01 10:36:21: Releasing resources... done
2024-10-01 10:36:21: Starting loop... done
error: PG::ConnectionBad: SSL SYSCALL error: EOF detected

/usr/local/rvm/gems/ruby-3.1.2/gems/pg-1.3.5/lib/pg/connection.rb:637:in `async_connect_or_reset'
/usr/local/rvm/gems/ruby-3.1.2/gems/pg-1.3.5/lib/pg/connection.rb:707:in `new'
/usr/local/rvm/gems/ruby-3.1.2/gems/sequel-5.56.0/lib/sequel/adapters/postgres.rb:208:in `connect'
/usr/local/rvm/gems/ruby-3.1.2/gems/sequel-5.56.0/lib/sequel/connection_pool.rb:122:in `make_new'
/usr/local/rvm/gems/ruby-3.1.2/gems/sequel-5.56.0/lib/sequel/connection_pool/threaded.rb:209:in `assign_connection'
/usr/local/rvm/gems/ruby-3.1.2/gems/sequel-5.56.0/lib/sequel/connection_pool/threaded.rb:139:in `acquire'
/usr/local/rvm/gems/ruby-3.1.2/gems/sequel-5.56.0/lib/sequel/connection_pool/threaded.rb:91:in `hold'
/usr/local/rvm/gems/ruby-3.1.2/gems/sequel-5.56.0/lib/sequel/database/connecting.rb:269:in `synchronize'
/usr/local/rvm/gems/ruby-3.1.2/gems/sequel-5.56.0/lib/sequel/adapters/postgres.rb:780:in `literal_string_append'
/usr/local/rvm/gems/ruby-3.1.2/gems/sequel-5.56.0/lib/sequel/dataset/sql.rb:82:in `literal_append'
/usr/local/rvm/gems/ruby-3.1.2/gems/sequel-5.56.0/lib/sequel/dataset/sql.rb:408:in `complex_expression_sql_append'
/usr/local/rvm/gems/ruby-3.1.2/gems/sequel-5.56.0/lib/sequel/adapters/shared/postgres.rb:1559:in `complex_expression_sql_append'
/usr/local/rvm/gems/ruby-3.1.2/gems/sequel-5.56.0/lib/sequel/model/associations.rb:3045:in `complex_expression_sql_append'
/usr/local/rvm/gems/ruby-3.1.2/gems/sequel-5.56.0/lib/sequel/sql.rb:112:in `to_s_append'
/usr/local/rvm/gems/ruby-3.1.2/gems/sequel-5.56.0/lib/sequel/dataset/sql.rb:1277:in `literal_expression_append'
/usr/local/rvm/gems/ruby-3.1.2/gems/sequel-5.56.0/lib/sequel/dataset/sql.rb:89:in `literal_append'
/usr/local/rvm/gems/ruby-3.1.2/gems/sequel-5.56.0/lib/sequel/dataset/sql.rb:416:in `block in complex_expression_sql_append'
/usr/local/rvm/gems/ruby-3.1.2/gems/sequel-5.56.0/lib/sequel/dataset/sql.rb:414:in `each'
/usr/local/rvm/gems/ruby-3.1.2/gems/sequel-5.56.0/lib/sequel/dataset/sql.rb:414:in `complex_expression_sql_append'
/usr/local/rvm/gems/ruby-3.1.2/gems/sequel-5.56.0/lib/sequel/adapters/shared/postgres.rb:1559:in `complex_expression_sql_append'
/usr/local/rvm/gems/ruby-3.1.2/gems/sequel-5.56.0/lib/sequel/model/associations.rb:3045:in `complex_expression_sql_append'
/usr/local/rvm/gems/ruby-3.1.2/gems/sequel-5.56.0/lib/sequel/sql.rb:112:in `to_s_append'
/usr/local/rvm/gems/ruby-3.1.2/gems/sequel-5.56.0/lib/sequel/dataset/sql.rb:1277:in `literal_expression_append'
/usr/local/rvm/gems/ruby-3.1.2/gems/sequel-5.56.0/lib/sequel/dataset/sql.rb:89:in `literal_append'
/usr/local/rvm/gems/ruby-3.1.2/gems/sequel-5.56.0/lib/sequel/dataset/sql.rb:1523:in `select_where_sql'
/usr/local/rvm/gems/ruby-3.1.2/gems/sequel-5.56.0/lib/sequel/dataset/sql.rb:250:in `select_sql'
/usr/local/rvm/gems/ruby-3.1.2/gems/sequel-5.56.0/lib/sequel/dataset/actions.rb:150:in `each'
/usr/local/rvm/gems/ruby-3.1.2/gems/sequel-5.56.0/lib/sequel/dataset/actions.rb:51:in `block in all'
/usr/local/rvm/gems/ruby-3.1.2/gems/sequel-5.56.0/lib/sequel/dataset/actions.rb:1010:in `_all'
/usr/local/rvm/gems/ruby-3.1.2/gems/sequel-5.56.0/lib/sequel/dataset/actions.rb:51:in `all'
/home/blackstack/code1/slave/extensions/mass.subaccount/p/launch2.rb:70:in `<main>'.
2024-10-01 10:37:21: Ending loop... done
2024-10-01 10:37:21: Calculating loop duration... done (60.116668068)
2024-10-01 10:37:21: Loop Finished!

2024-10-01 10:37:21: No sleeping. The loop took 60.116668068 seconds.
2024-10-01 10:37:21: Releasing resources... done
2024-10-01 10:37:22: Starting loop... done
```

**Comment by leandrosardi** [comment]
If you are running in your locan environment, remember to do `touch .sandbox` into the folder `/home/blackstack/sdk/p`.
