### ISSUE TITLE
glitch: SDK - Facebook pictures URLs expored - I have to renew them.

### ISSUE THREAD

**Issue by leandrosardi** [MassProspecting/docs#304]
```
leandro@dev2:~/code1/sdk/p$ export RUBYLIB=~/code1/sdk
leandro@dev2:~/code1/sdk/p$ ruby submit2.rb
2024-10-10 09:24:35: Checking for duplicated API keys... ok
2024-10-10 09:24:35: Checking for duplicated MTA keys... ok
2024-10-10 09:24:36: Checking for duplicated RPA keys... ok
2024-10-10 09:24:36: Upserting API Profile: Reoon LTD 01 - 300 Verifications Daily... done
2024-10-10 09:24:37: Upserting API Profile: Reoon LTD 02 - 300 Verifications Daily... done
2024-10-10 09:24:37: Upserting API Profile: Reoon LTD 03 - 300 Verifications Daily... done
2024-10-10 09:24:37: Upserting API Profile: Reoon LTD 04 - 300 Verifications Daily... done
2024-10-10 09:24:37: Upserting API Profile: Reoon LTD 05 - 300 Verifications Daily... done
2024-10-10 09:24:37: Upserting API Profile: Reoon LTD 06 - 300 Verifications Daily... done
2024-10-10 09:24:37: Upserting API Profile: Reoon LTD 07 - 300 Verifications Daily... done
2024-10-10 09:24:37: Upserting API Profile: ZeroBounce - 100 Verifications / Month... done
2024-10-10 09:24:38: Upserting MTA Profile: Leandro Sardi... done
2024-10-10 09:24:38: Upserting MTA Profile: Leandro Sardi... done
2024-10-10 09:24:38: Upserting MTA Profile: Amy Blain A.... done
2024-10-10 09:24:38: Upserting MTA Profile: Amy Blain B.... done
2024-10-10 09:24:39: Upserting MTA Profile: Amy Blain C.... done
2024-10-10 09:24:39: Upserting MTA Profile: Amy Blain D.... done
2024-10-10 09:24:39: Upserting MTA Profile: Amy Blain E.... done
2024-10-10 09:24:39: Upserting MTA Profile: Amy Blain F.... done
2024-10-10 09:24:39: Upserting MTA Profile: Amy Blain G.... done
2024-10-10 09:24:39: Upserting MTA Profile: Amy Blain H.... done
2024-10-10 09:24:39: Upserting MTA Profile: Amy Blain I.... done
2024-10-10 09:24:39: Upserting MTA Profile: Amy Blain K.... done
2024-10-10 09:24:39: Upserting MTA Profile: Amy Blain M.... done
2024-10-10 09:24:39: Upserting MTA Profile: Amy Blain N.... done
2024-10-10 09:24:39: Upserting MTA Profile: Amy Blain O.... done
2024-10-10 09:24:39: Upserting MTA Profile: Amy Blain P.... done
2024-10-10 09:24:39: Upserting MTA Profile: Amy Blain Q.... done
2024-10-10 09:24:39: Upserting RPA Profile: Apollo.02... done
2024-10-10 09:24:40: Upserting RPA Profile: Deborah J.... done
2024-10-10 09:24:40: Upserting RPA Profile: Apollo.03... done
2024-10-10 09:24:40: Upserting RPA Profile: Apollo.04... done
2024-10-10 09:24:40: Upserting RPA Profile: Apollo.05... done
2024-10-10 09:24:40: Upserting RPA Profile: Haris Khan... done
2024-10-10 09:24:40: Upserting RPA Profile: Mary Adu... done
2024-10-10 09:24:41: Upserting RPA Profile: Gertrude Nworie... done
2024-10-10 09:24:41: Upserting RPA Profile: Gertrude Nworie... error: Error calling upsert endpoint: The picture_url 'https://scontent-ams2-1.xx.fbcdn.net/v/t39.30808-6/412122409_928425068699149_3855943407917571993_n.jpg?_nc_cat=100&ccb=1-7&_nc_sid=6ee11a&_nc_ohc=ibzlOEiHCywQ7kNvgFqqbfh&_nc_ht=scontent-ams2-1.xx&_nc_gid=A0Ni5Di-fQWGldhuo8_MtXR&oh=00_AYBksBZo8uk2BXPfIkA-bLohmSXUwZuCP_ni9S7t8KcElA&oe=67048676' for Profile is not reachable.
/home/leandro/.rvm/gems/ruby-3.1.2/gems/blackstack-core-1.2.28/lib/functions.rb:247:in `upsert'
submit2.rb:85:in `block in <main>'
submit2.rb:82:in `each'
submit2.rb:82:in `<main>'.
```

![Image](https://github.com/user-attachments/assets/699c3a34-4a88-4bf0-a9f3-9c001c1c46c1)

**Comment by leandrosardi** [comment]
I think this problem was resolved, by using a buffer column to save the original URL and don't download the picture again and again.
