### ISSUE TITLE
glitch: Apollo enrichment

### ISSUE THREAD

**Issue by leandrosardi** [MassProspecting/docs#317]
```
ruby profile.rb api_key=07e17fd3-6af1-4bf9-b2bf-faed2c81f51f api_url=https://s01.massprospecting.com:443 id=716ed7e9-6a25-4249-8f77-d1e000bcac06 ignore-hostname=yes force-profile-run=yes headless=no run-once=yes inboxcheck=no connectioncheck=no scraping=no enrichment=yes id_enrichment=02cc4330-a047-4c34-a44a-cef446afd692 outreach=no 
```

```
element click intercepted: Element  is not clickable at point (1018, 57). Other element would receive the click: 
  (Session info: chrome=116.0.5845.97)
#0 0x55a74c2b5e23 
#1 0x55a74bfde7a7 
#2 0x55a74c022d22 
#3 0x55a74c021267 
#4 0x55a74c01f1e8 
#5 0x55a74c01e32d 
#6 0x55a74c013599 
#7 0x55a74c03e012 
#8 0x55a74c012fb6 
#9 0x55a74c03e1de 
#10 0x55a74c056369 
#11 0x55a74c03dde3 
#12 0x55a74c011a7b 
#13 0x55a74c01281e 
#14 0x55a74c277638 
#15 0x55a74c27b507 
#16 0x55a74c285c4c 
#17 0x55a74c27c136 
#18 0x55a74c24a9cf 
#19 0x55a74c29fb98 
#20 0x55a74c29fd68 
#21 0x55a74c2aecb3 
#22 0x7f3540f8d609 start_thread
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/response.rb:55:in `assert_ok'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/http/common.rb:83:in `new'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/http/common.rb:83:in `create_response'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/http/default.rb:104:in `request'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/bridge.rb:620:in `execute'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/bridge.rb:390:in `click_element'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/common/element.rb:77:in `click'
/home/blackstack/code1/sdk/lib/profile_rpa/apollo_rpa.rb:185:in `people_search_row_to_lead_hash'
/home/blackstack/code1/sdk/lib/enrichment_types/ApolloRPA_Enrichment.rb:110:in `block in scrape'
/home/blackstack/code1/sdk/lib/enrichment_types/ApolloRPA_Enrichment.rb:103:in `each'
/home/blackstack/code1/sdk/lib/enrichment_types/ApolloRPA_Enrichment.rb:103:in `scrape'
/home/blackstack/code1/sdk/lib/enrichment_types/ApolloRPA_NameAndLinkedInUrlToEmail.rb:36:in `do'
/home/blackstack/code1/sdk/p/profile.rb:901:in `block in 
'
/home/blackstack/code1/sdk/p/profile.rb:893:in `each'
/home/blackstack/code1/sdk/p/profile.rb:893:in `
'
```

![Image](https://github.com/user-attachments/assets/1334933f-bc2c-4736-975f-4615363bbcee)

**Comment by leandrosardi** [comment]
Fixed with #316.
