### ISSUE TITLE
glitch: `unexpected token at ''`

### ISSUE THREAD

**Issue by leandrosardi** [MassProspecting/docs#321]
```
ruby profile.rb api_key=07e17fd3-6af1-4bf9-b2bf-faed2c81f51f api_url=https://s01.massprospecting.com:443 id=5fa0ad4b-5797-4470-baf4-fa9ebc09f7f1 ignore-hostname=yes force-profile-run=yes headless=no run-once=yes inboxcheck=no connectioncheck=no scraping=yes id_job=40cb404f-9e9a-4482-8342-1d398ef626e3 enrichment=no outreach=no 
```

```
unexpected token at ''
/usr/local/rvm/gems/ruby-3.1.2/gems/json-2.6.3/lib/json/common.rb:216:in `parse'
/usr/local/rvm/gems/ruby-3.1.2/gems/json-2.6.3/lib/json/common.rb:216:in `parse'
/usr/local/rvm/gems/ruby-3.1.2/gems/my-dropbox-api-1.0.2/lib/my-dropbox-api.rb:226:in `get_file_url'
/usr/local/rvm/gems/ruby-3.1.2/gems/mass-client-1.0.20/lib/first-line/profile_rpa.rb:311:in `screenshot'
/usr/local/rvm/gems/ruby-3.1.2/gems/mass-client-1.0.20/lib/base-line/source.rb:116:in `show_up_event_elements'
/home/blackstack/code1/sdk/lib/source_types/LinkedIn_PublicFeed.rb:144:in `do'
/home/blackstack/code1/sdk/p/profile.rb:772:in `block in 
'
/home/blackstack/code1/sdk/p/profile.rb:764:in `each'
/home/blackstack/code1/sdk/p/profile.rb:764:in `
'
```

**Comment by leandrosardi** [comment]
Related with #320.
