### ISSUE TITLE
Test & Result PostMark Integration

### ISSUE THREAD

**Issue by leandrosardi** [MassProspecting/docs#327]
## Postmark

Already developed... just pending to test.

## Testng CLI command

```
ruby profile.rb api_key=d81f8435-5da3-4c16-9bc5-cb6646974d51 api_url=http://127.0.0.1:3001 id=cf5d3209-a89e-487c-ab9e-050a559ee94b ignore-hostname=yes force-profile-run=yes headless=no run-once=yes inboxcheck=no connectioncheck=no scraping=no enrichment=no outreach=yes id_outreach=03105b78-b5af-4e70-ab8d-78185edfc43c 
```

## Error

```
Network is unreachable - connect(2) for [2800:3f0:4003:c02::6d]:25
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/socket.rb:1214:in `__connect_nonblock'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/socket.rb:1214:in `connect_nonblock'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/socket.rb:56:in `connect_internal'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/socket.rb:137:in `connect'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/socket.rb:642:in `block in tcp'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/socket.rb:227:in `each'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/socket.rb:227:in `foreach'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/socket.rb:632:in `tcp'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/net-smtp-0.3.1/lib/net/smtp.rb:626:in `tcp_socket'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/net-smtp-0.3.1/lib/net/smtp.rb:639:in `do_start'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/net-smtp-0.3.1/lib/net/smtp.rb:604:in `start'
/usr/local/rvm/gems/ruby-3.1.2/gems/mail-2.7.1/lib/mail/network/delivery_methods/smtp.rb:109:in `start_smtp_session'
/usr/local/rvm/gems/ruby-3.1.2/gems/mail-2.7.1/lib/mail/network/delivery_methods/smtp.rb:100:in `deliver!'
/usr/local/rvm/gems/ruby-3.1.2/gems/mail-2.7.1/lib/mail/message.rb:2159:in `do_delivery'
/usr/local/rvm/gems/ruby-3.1.2/gems/mail-2.7.1/lib/mail/message.rb:262:in `deliver'
/home/blackstack/code1/sdk/lib/outreach_types/MTA_DirectMessage.rb:77:in `do'
profile.rb:1126:in `block in 
'
profile.rb:1042:in `each'
profile.rb:1042:in `
```

**Comment by leandrosardi** [comment]
## MailReef.com

This providers requires `enable_starttls_auto=false` but such a parameters is not being mapped correctly from the database (it is always `true`)

Also, I have to hardcode a new parameter for this provider: `ssl=true`.

**Comment by leandrosardi** [comment]
> Network is unreachable - connect(2) for [2800:3f0:4003:c02::6d]:25

This problem fixed after I deletred the old API key (from 2017) and I created a new one.

**Comment by leandrosardi** [comment]
## Problems

1. Postmark doesn't provide IMAP or POP services. 
Responses are received in GMail/GSuite.

![Image](https://github.com/user-attachments/assets/4d38ec06-08e6-4ae2-95f0-4e4003f23fe9)

So, PostMark is used for outreach only, and I need to setup another GSuite/GMail integration for receiving responses.

2. The `smtp_username` is used for both: login the SMTP server and set the sender email address.
That is a problem when Postmark requires the API key into the `smtp_username`.

**Comment by leandrosardi** [comment]
## Problem 3

InboxCheck is failing because PostMark doesn't support IMAP/POP services:

```
blackstack@dev2:~/code1/sdk/p$ ruby profile.rb api_key=d81f8435-5da3-4c16-9bc5-cb6646974d51 api_url=http://127.0.0.1:3001 id=cf5d3209-a89e-487c-ab9e-050a559ee94b ignore-hostname=yes force-profile-run=yes headless=no run-once=yes inboxcheck=yes id_inboxcheck=9fc607bd-85e0-4c16-bdb9-5efee9498ce3 connectioncheck=no scraping=no enrichment=no outreach=no 
2025-01-24 09:14:50: Starting loop... done
2025-01-24 09:14:50: Loading profile cf5d3209-a89e-487c-ab9e-050a559ee94b... done
2025-01-24 09:14:50: Is profile assigned to this host?... yes
2025-01-24 09:14:50: Loading profile type (Postmark)... done
2025-01-24 09:14:50: Is profile under revision?... no
2025-01-24 09:14:50: Is Postmark a rpa... no
2025-01-24 09:14:50: Getting the next request to process... done (0 requests)
2025-01-24 09:14:50: Is Postmark a rpa... no
2025-01-24 09:14:50: Inboxcheck... yes
2025-01-24 09:14:50: Set profile state :scraping_inbox... skip (force-profile-run is on)
2025-01-24 09:14:50: Mark inboxcheck as :running... done
2025-01-24 09:14:50: Connecting IMAP... 2025-01-24 09:14:51: Error: Invalid credentials (Failure)
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/net-imap-0.2.3/lib/net/imap.rb:1245:in `get_tagged_response'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/net-imap-0.2.3/lib/net/imap.rb:1299:in `block in send_command'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/monitor.rb:202:in `synchronize'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/monitor.rb:202:in `mon_synchronize'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/net-imap-0.2.3/lib/net/imap.rb:1281:in `send_command'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/net-imap-0.2.3/lib/net/imap.rb:422:in `login'
/usr/local/rvm/gems/ruby-3.1.2/gems/mass-client-1.0.29/lib/first-line/profile_mta.rb:51:in `inboxcheck'
profile.rb:486:in `block in <main>'
profile.rb:479:in `each'
profile.rb:479:in `<main>'done
2025-01-24 09:14:51: Taking screenshot... skip (not a rpa)
2025-01-24 09:14:51: Taking snapshot... skip (not a rpa)
2025-01-24 09:14:51: Updating job... done
2025-01-24 09:14:51: Error: Invalid credentials (Failure)
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/net-imap-0.2.3/lib/net/imap.rb:1245:in `get_tagged_response'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/net-imap-0.2.3/lib/net/imap.rb:1299:in `block in send_command'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/monitor.rb:202:in `synchronize'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/monitor.rb:202:in `mon_synchronize'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/net-imap-0.2.3/lib/net/imap.rb:1281:in `send_command'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/net-imap-0.2.3/lib/net/imap.rb:422:in `login'
/usr/local/rvm/gems/ruby-3.1.2/gems/mass-client-1.0.29/lib/first-line/profile_mta.rb:51:in `inboxcheck'
profile.rb:486:in `block in <main>'
profile.rb:479:in `each'
profile.rb:479:in `<main>'
```

**Comment by leandrosardi** [comment]
## Solution to Problem 1 and Problem 3

Request both passwords when add a new MTA integration: smtp_password and imap_password.
