### ISSUE TITLE
glitch: Selenium protocol timeout issue.

### ISSUE THREAD

**Issue by leandrosardi** [MassProspecting/docs#332]
```
Net::ReadTimeout with #
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/net/protocol.rb:219:in `rbuf_fill'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/net/protocol.rb:193:in `readuntil'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/net/protocol.rb:203:in `readline'
/usr/local/rvm/gems/ruby-3.1.2/gems/net-http-0.2.2/lib/net/http/response.rb:42:in `read_status_line'
/usr/local/rvm/gems/ruby-3.1.2/gems/net-http-0.2.2/lib/net/http/response.rb:31:in `read_new'
/usr/local/rvm/gems/ruby-3.1.2/gems/net-http-0.2.2/lib/net/http.rb:1615:in `block in transport_request'
/usr/local/rvm/gems/ruby-3.1.2/gems/net-http-0.2.2/lib/net/http.rb:1606:in `catch'
/usr/local/rvm/gems/ruby-3.1.2/gems/net-http-0.2.2/lib/net/http.rb:1606:in `transport_request'
/usr/local/rvm/gems/ruby-3.1.2/gems/net-http-0.2.2/lib/net/http.rb:1579:in `request'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/http/default.rb:119:in `response_for'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/http/default.rb:77:in `request'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/bridge.rb:620:in `execute'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/bridge.rb:258:in `set_window_rect'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/bridge.rb:216:in `resize_window'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/common/window.rb:119:in `resize_to'
/usr/local/rvm/gems/ruby-3.1.2/gems/mass-client-1.0.25/lib/first-line/profile_rpa.rb:308:in `driver'
/home/blackstack/code1/sdk/lib/profile_rpa/apollo_rpa.rb:14:in `block in wait_results'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/common/wait.rb:56:in `until'
/home/blackstack/code1/sdk/lib/profile_rpa/apollo_rpa.rb:12:in `wait_results'
/home/blackstack/code1/sdk/lib/enrichment_types/ApolloRPA_Enrichment.rb:51:in `scrape'
/home/blackstack/code1/sdk/lib/enrichment_types/ApolloRPA_NameAndLinkedInUrlToEmail.rb:36:in `do'
/home/blackstack/code1/sdk/p/profile.rb:901:in `block in 
'
/home/blackstack/code1/sdk/p/profile.rb:893:in `each'
/home/blackstack/code1/sdk/p/profile.rb:893:in `
```

**Comment by leandrosardi** [comment]
```
Net::ReadTimeout with #
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/net/protocol.rb:219:in `rbuf_fill'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/net/protocol.rb:193:in `readuntil'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/net/protocol.rb:203:in `readline'
/usr/local/rvm/gems/ruby-3.1.2/gems/net-http-0.2.2/lib/net/http/response.rb:42:in `read_status_line'
/usr/local/rvm/gems/ruby-3.1.2/gems/net-http-0.2.2/lib/net/http/response.rb:31:in `read_new'
/usr/local/rvm/gems/ruby-3.1.2/gems/net-http-0.2.2/lib/net/http.rb:1615:in `block in transport_request'
/usr/local/rvm/gems/ruby-3.1.2/gems/net-http-0.2.2/lib/net/http.rb:1606:in `catch'
/usr/local/rvm/gems/ruby-3.1.2/gems/net-http-0.2.2/lib/net/http.rb:1606:in `transport_request'
/usr/local/rvm/gems/ruby-3.1.2/gems/net-http-0.2.2/lib/net/http.rb:1579:in `request'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/http/default.rb:119:in `response_for'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/http/default.rb:77:in `request'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/bridge.rb:620:in `execute'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/bridge.rb:94:in `get'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/common/navigation.rb:32:in `to'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/common/driver.rb:135:in `get'
/home/blackstack/code1/sdk/lib/enrichment_types/ApolloRPA_Enrichment.rb:47:in `scrape'
/home/blackstack/code1/sdk/lib/enrichment_types/ApolloRPA_NameAndLinkedInUrlToEmail.rb:36:in `do'
/home/blackstack/code1/sdk/p/profile.rb:901:in `block in 
'
/home/blackstack/code1/sdk/p/profile.rb:893:in `each'
/home/blackstack/code1/sdk/p/profile.rb:893:in `
'
```

**Comment by leandrosardi** [comment]
```
Net::ReadTimeout with #
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/net/protocol.rb:219:in `rbuf_fill'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/net/protocol.rb:193:in `readuntil'
/usr/local/rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/net/protocol.rb:203:in `readline'
/usr/local/rvm/gems/ruby-3.1.2/gems/net-http-0.2.2/lib/net/http/response.rb:42:in `read_status_line'
/usr/local/rvm/gems/ruby-3.1.2/gems/net-http-0.2.2/lib/net/http/response.rb:31:in `read_new'
/usr/local/rvm/gems/ruby-3.1.2/gems/net-http-0.2.2/lib/net/http.rb:1615:in `block in transport_request'
/usr/local/rvm/gems/ruby-3.1.2/gems/net-http-0.2.2/lib/net/http.rb:1606:in `catch'
/usr/local/rvm/gems/ruby-3.1.2/gems/net-http-0.2.2/lib/net/http.rb:1606:in `transport_request'
/usr/local/rvm/gems/ruby-3.1.2/gems/net-http-0.2.2/lib/net/http.rb:1579:in `request'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/http/default.rb:119:in `response_for'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/http/default.rb:77:in `request'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/bridge.rb:620:in `execute'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/remote/bridge.rb:94:in `get'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/common/navigation.rb:32:in `to'
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/common/driver.rb:135:in `get'
/home/blackstack/code1/sdk/lib/enrichment_types/ApolloRPA_Enrichment.rb:47:in `scrape'
/home/blackstack/code1/sdk/lib/enrichment_types/ApolloRPA_NameAndLinkedInUrlToEmail.rb:36:in `do'
/home/blackstack/code1/sdk/p/profile.rb:901:in `block in 
'
/home/blackstack/code1/sdk/p/profile.rb:893:in `each'
/home/blackstack/code1/sdk/p/profile.rb:893:in `
'
```
