### ISSUE TITLE
glitch: LinkedIn_PublicFeed selenium timeout

### ISSUE THREAD

**Issue by leandrosardi** [MassProspecting/docs#335]
```
timed out after 10 seconds
/usr/local/rvm/gems/ruby-3.1.2/gems/selenium-webdriver-4.10.0/lib/selenium/webdriver/common/wait.rb:73:in `until'
/home/blackstack/code1/sdk/lib/source_types/LinkedIn_PublicFeed.rb:219:in `block in do'
/home/blackstack/code1/sdk/lib/source_types/LinkedIn_PublicFeed.rb:165:in `each'
/home/blackstack/code1/sdk/lib/source_types/LinkedIn_PublicFeed.rb:165:in `do'
/home/blackstack/code1/sdk/p/profile.rb:782:in `block in 
'
/home/blackstack/code1/sdk/p/profile.rb:774:in `each'
/home/blackstack/code1/sdk/p/profile.rb:774:in `
'
```

**Comment by leandrosardi** [comment]
Related with #334
