### ISSUE TITLE
Test & Fix: Automatic first followup after connection request acceptance, avoiding repliers, avoiding previous events

### ISSUE THREAD

**Issue by leandrosardi** [MassProspecting/docs#342]
## Problem

![image](https://github.com/user-attachments/assets/699d60bb-8ca6-49fc-97d4-952ab735d8a3)

```
undefined method `id' for nil:NilClass

            o.id_outreach_type = Mass::OutreachType.where(:id_account => h['id_account'], :name => h['outreach_type'].to_s, :delete_time => nil).first.id if ['outreach_done', 'accepted_request'].include?(h['type'].to_s)
                                                                                                                                                      ^^^
/home/leandro/code1/slave/extensions/mass.subaccount/models/skeleton/trigger.rb:108:in `update'
/home/leandro/code1/slave/lib/skeletons.rb:61:in `insert'
/home/leandro/code1/slave/extensions/mass.subaccount/models/skeleton/rule.rb:250:in `update'
/home/leandro/code1/slave/lib/skeletons.rb:61:in `insert'
./extensions/mass.subaccount/views/ajax/rules/create.erb:14:in `__tilt_47940'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/tilt-2.4.0/lib/tilt/template.rb:207:in `bind_call'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/tilt-2.4.0/lib/tilt/template.rb:207:in `evaluate'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/tilt-2.4.0/lib/tilt/template.rb:102:in `render'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/base.rb:863:in `render'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/base.rb:711:in `erb'
/home/leandro/code1/slave/extensions/mass.subaccount/app.rb:443:in `block in '
/home/leandro/.rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/base.rb:1697:in `call'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/base.rb:1697:in `block in compile!'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/base.rb:1030:in `block (3 levels) in route!'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/base.rb:1049:in `route_eval'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/base.rb:1030:in `block (2 levels) in route!'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/base.rb:1078:in `block in process_route'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/base.rb:1076:in `catch'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/base.rb:1076:in `process_route'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/base.rb:1028:in `block in route!'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/base.rb:1025:in `each'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/base.rb:1025:in `route!'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/base.rb:1147:in `block in dispatch!'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/base.rb:1119:in `block in invoke'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/base.rb:1119:in `catch'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/base.rb:1119:in `invoke'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/base.rb:1142:in `dispatch!'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/base.rb:956:in `block in call!'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/base.rb:1119:in `block in invoke'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/base.rb:1119:in `catch'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/base.rb:1119:in `invoke'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/base.rb:956:in `call!'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/base.rb:945:in `call'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/rack-contrib-2.3.0/lib/rack/contrib/try_static.rb:35:in `call'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/rack-contrib-2.3.0/lib/rack/contrib/try_static.rb:35:in `call'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/rack-contrib-2.3.0/lib/rack/contrib/try_static.rb:35:in `call'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/rack-contrib-2.3.0/lib/rack/contrib/try_static.rb:35:in `call'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/rack-contrib-2.3.0/lib/rack/contrib/try_static.rb:35:in `call'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/rack-2.2.10/lib/rack/session/abstract/id.rb:266:in `context'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/rack-2.2.10/lib/rack/session/abstract/id.rb:260:in `call'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/rack-2.2.10/lib/rack/logger.rb:17:in `call'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/rack-2.2.10/lib/rack/common_logger.rb:38:in `call'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/base.rb:255:in `call'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/base.rb:248:in `call'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/rack-2.2.10/lib/rack/head.rb:12:in `call'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/rack-2.2.10/lib/rack/method_override.rb:24:in `call'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/show_exceptions.rb:22:in `call'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/base.rb:218:in `call'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/base.rb:2004:in `call'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/base.rb:1564:in `block in call'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/base.rb:1780:in `synchronize'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/sinatra-2.2.4/lib/sinatra/base.rb:1564:in `call'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/puma-5.6.9/lib/puma/configuration.rb:252:in `call'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/puma-5.6.9/lib/puma/request.rb:77:in `block in handle_request'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/puma-5.6.9/lib/puma/thread_pool.rb:340:in `with_force_shutdown'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/puma-5.6.9/lib/puma/request.rb:76:in `handle_request'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/puma-5.6.9/lib/puma/server.rb:443:in `process_client'
/home/leandro/.rvm/gems/ruby-3.1.2/gems/puma-5.6.9/lib/puma/thread_pool.rb:147:in `block in spawn_thread'
```

**Comment by leandrosardi** [comment]
## Testing Queries

```sql
-- Rule 4b
select t.name, l.first_name, l.last_name, p.name, o.create_time, o.done_time, o.direction, o.body 
--select count(distinct i.id) as instances, count(distinct l.id) as leads, count(distinct o.id) as outreaches
from rule_instance i
join lead_tag x on i.id=x.id_rule_instance_create
join "tag" t on t.id=x.id_tag
join "lead" l on l.id=x.id_lead 
join "outreach" o on l.id=o.id_lead
join rule_instance i2 on (i2.id=o.id_rule_instance and i2.id_rule='1d6f0f56-4cfa-4c0a-b233-7382c09ab9e5') -- 4a (sending connection request)
join "profile" p on p.id=o.id_profile 
where i.id_rule='bc9b7a0e-33ee-4a74-b4f0-373cd3acfc1c' -- 4b
order by l.first_name, l.last_name, o.create_time
```

```sql
-- Rule 4c
select t.name, l.first_name, l.last_name, p.name, o.create_time, o.done_time, o.direction, o.body 
--select count(distinct i.id) as instances, count(distinct l.id) as leads, count(distinct o.id) as outreaches
from rule_instance i
join lead_tag x on i.id=x.id_rule_instance_create
join "tag" t on t.id=x.id_tag
join "lead" l on l.id=x.id_lead 
join "outreach" o on l.id=o.id_lead
join rule_instance i2 on (i2.id=o.id_rule_instance and i2.id_rule='1d6f0f56-4cfa-4c0a-b233-7382c09ab9e5') -- 4a (sending connection request)
join "profile" p on p.id=o.id_profile 
where i.id_rule='5c1c1038-01a5-4afc-a6db-395f79500b53' -- 4c
order by l.first_name, l.last_name, o.create_time
```
